language: python
python: "2.7"
addons:
  mariadb: "10.1"
install:
  - "pip install openedoo"
  - "openedoo install"
  - "cd openedoo_project"
  - "python manage.py module install https://github.com/openedoo/module_eclass.git"
  - "python -m unittest discover modules/module_eclass"
